/*
Copyright 2018 The Argo Project Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/argoproj/argo-events/pkg/apis/events/v1alpha1"
	scheme "github.com/argoproj/argo-events/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// WiresGetter has a method to return a WireInterface.
// A group's client should implement this interface.
type WiresGetter interface {
	Wires(namespace string) WireInterface
}

// WireInterface has methods to work with Wire resources.
type WireInterface interface {
	Create(*v1alpha1.Wire) (*v1alpha1.Wire, error)
	Update(*v1alpha1.Wire) (*v1alpha1.Wire, error)
	UpdateStatus(*v1alpha1.Wire) (*v1alpha1.Wire, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Wire, error)
	List(opts v1.ListOptions) (*v1alpha1.WireList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Wire, err error)
	WireExpansion
}

// wires implements WireInterface
type wires struct {
	client rest.Interface
	ns     string
}

// newWires returns a Wires
func newWires(c *ArgoprojV1alpha1Client, namespace string) *wires {
	return &wires{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the wire, and returns the corresponding wire object, and an error if there is any.
func (c *wires) Get(name string, options v1.GetOptions) (result *v1alpha1.Wire, err error) {
	result = &v1alpha1.Wire{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("wires").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Wires that match those selectors.
func (c *wires) List(opts v1.ListOptions) (result *v1alpha1.WireList, err error) {
	result = &v1alpha1.WireList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("wires").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested wires.
func (c *wires) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("wires").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a wire and creates it.  Returns the server's representation of the wire, and an error, if there is any.
func (c *wires) Create(wire *v1alpha1.Wire) (result *v1alpha1.Wire, err error) {
	result = &v1alpha1.Wire{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("wires").
		Body(wire).
		Do().
		Into(result)
	return
}

// Update takes the representation of a wire and updates it. Returns the server's representation of the wire, and an error, if there is any.
func (c *wires) Update(wire *v1alpha1.Wire) (result *v1alpha1.Wire, err error) {
	result = &v1alpha1.Wire{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("wires").
		Name(wire.Name).
		Body(wire).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *wires) UpdateStatus(wire *v1alpha1.Wire) (result *v1alpha1.Wire, err error) {
	result = &v1alpha1.Wire{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("wires").
		Name(wire.Name).
		SubResource("status").
		Body(wire).
		Do().
		Into(result)
	return
}

// Delete takes name of the wire and deletes it. Returns an error if one occurs.
func (c *wires) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("wires").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *wires) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("wires").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched wire.
func (c *wires) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Wire, err error) {
	result = &v1alpha1.Wire{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("wires").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
