/*
Copyright 2018 The Argo Project Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/argoproj/argo-events/pkg/apis/events/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWires implements WireInterface
type FakeWires struct {
	Fake *FakeArgoprojV1alpha1
	ns   string
}

var wiresResource = schema.GroupVersionResource{Group: "argoproj.io", Version: "v1alpha1", Resource: "wires"}

var wiresKind = schema.GroupVersionKind{Group: "argoproj.io", Version: "v1alpha1", Kind: "Wire"}

// Get takes name of the wire, and returns the corresponding wire object, and an error if there is any.
func (c *FakeWires) Get(name string, options v1.GetOptions) (result *v1alpha1.Wire, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(wiresResource, c.ns, name), &v1alpha1.Wire{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Wire), err
}

// List takes label and field selectors, and returns the list of Wires that match those selectors.
func (c *FakeWires) List(opts v1.ListOptions) (result *v1alpha1.WireList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(wiresResource, wiresKind, c.ns, opts), &v1alpha1.WireList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WireList{}
	for _, item := range obj.(*v1alpha1.WireList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested wires.
func (c *FakeWires) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(wiresResource, c.ns, opts))

}

// Create takes the representation of a wire and creates it.  Returns the server's representation of the wire, and an error, if there is any.
func (c *FakeWires) Create(wire *v1alpha1.Wire) (result *v1alpha1.Wire, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(wiresResource, c.ns, wire), &v1alpha1.Wire{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Wire), err
}

// Update takes the representation of a wire and updates it. Returns the server's representation of the wire, and an error, if there is any.
func (c *FakeWires) Update(wire *v1alpha1.Wire) (result *v1alpha1.Wire, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(wiresResource, c.ns, wire), &v1alpha1.Wire{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Wire), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWires) UpdateStatus(wire *v1alpha1.Wire) (*v1alpha1.Wire, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(wiresResource, "status", c.ns, wire), &v1alpha1.Wire{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Wire), err
}

// Delete takes name of the wire and deletes it. Returns an error if one occurs.
func (c *FakeWires) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(wiresResource, c.ns, name), &v1alpha1.Wire{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWires) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(wiresResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.WireList{})
	return err
}

// Patch applies the patch and returns the patched wire.
func (c *FakeWires) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Wire, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(wiresResource, c.ns, name, data, subresources...), &v1alpha1.Wire{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Wire), err
}
